/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddMemoryModal: typeof import('./components/public/AddMemoryModal.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BarChart: typeof import('./components/admin/BarChart.vue')['default']
    DataTable: typeof import('./components/admin/DataTable.vue')['default']
    DeceasedForm: typeof import('./components/admin/DeceasedForm.vue')['default']
    DeceasedRow: typeof import('./components/admin/DeceasedRow.vue')['default']
    GuardianForm: typeof import('./components/admin/GuardianForm.vue')['default']
    GuardianRow: typeof import('./components/admin/GuardianRow.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    KpiCard: typeof import('./components/admin/KpiCard.vue')['default']
    LangToggle: typeof import('./components/ui/LangToggle.vue')['default']
    LineChart: typeof import('./components/admin/LineChart.vue')['default']
    MemorialCard: typeof import('./components/public/MemorialCard.vue')['default']
    MemoryCard: typeof import('./components/public/MemoryCard.vue')['default']
    PaginationControl: typeof import('./components/ui/PaginationControl.vue')['default']
    PendingMemoryCard: typeof import('./components/guardian/PendingMemoryCard.vue')['default']
    PieChart: typeof import('./components/admin/PieChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeToggle: typeof import('./components/ui/ThemeToggle.vue')['default']
    ToastNotification: typeof import('./components/ui/ToastNotification.vue')['default']
  }
}
